version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-db
    stdin_open: true
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - '/app/node_modules'


  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3307:3306"
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

volumes:
  db-config:
  db-data:
